### ISSUE TITLE
Enabling fast seek for files opened in write or read-write mode is wrong

### ISSUE THREAD

**Issue by adokitkat** [drorgl/esp32-sd-card-benchmarks#1]
Hi! First of all thank you for comprehensive benchmarks. 

One of your modifications is:

```c
if(!(fat_mode_conv(flags) & (FA_WRITE))) {
    DWORD *clmt_mem =  ff_memalloc(sizeof(DWORD) * CONFIG_FATFS_FAST_SEEK_BUFFER_SIZE);
```

to:

```c
if((fat_mode_conv(flags) & (FA_READ))) {
    DWORD *clmt_mem =  ff_memalloc(sizeof(DWORD) * CONFIG_FATFS_FAST_SEEK_BUFFER_SIZE);
```

However I think you shouldn't be doing this. You are enabling fast seek even for files in read-write mode, which shouldn't be done because write can change the size of the file and the constructed cluster link map table would have wrong data inside. You should close the file first and open it in read-only mode to use fast seek.

You can enable fast seek by configuring [CONFIG_FATFS_USE_FASTSEEK](https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/api-reference/kconfig.html#config-fatfs-use-fastseek) via `idf.py menuconfig` or in sdkconfig file. Then it will be automatically used for files opened in read-only mode.

**Comment by drorgl** [comment]
You are correct.

The intended use for the benchmarks was to test for some sort of swap file (for the ESP32 tinyemu port), The file was created at a specific size and random writes should seek quickly, so in this case the code is correct since the file was opened with read/write mode.
